name: Update snapshots

on:
  pull_request:
    branches: [main]

env:
  FC_DEBUG: 1

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: npx playwright install --with-deps chromium
      - run: yarn ci:ui:update

  check-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: npx playwright install --with-deps chromium
      - run: fc-list
      - run: yarn ci:ui
