name: Update snapshots

on:
  pull_request:
    branches: [main]

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          # cache: 'yarn' # doesn't work with `act`, so not useful for running locally :/
      - run: yarn install
      - run: npx playwright install-deps chromium
      - run: yarn ci:ui:update
