name: Update snapshots

on:
  pull_request:
    branches: [main]

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: yarn ci:ui:update

  check-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: fc-list
      - run: ls -al /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
      - run: yarn install
      - run: yarn ci:ui
